name: Gradle CI

on:
  push:
    branches: [ mirai-v2.4.0 ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ mirai-v2.4.0 ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone repository

    - name: Prepare Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build project
      run: |
        gradle wrapper
        bash gradlew shadow
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: onebot-mirai
        path: onebot-mirai/build/libs/onebot-mirai-*-all.jar

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: onebot-kotlin
        path: onebot-kotlin/build/libs/onebot-kotlin-*-all.jar
